### ISSUE TITLE
Cannot use import statement outside a module on version 0.10.7

### ISSUE THREAD

**Issue by Ionut-Milas** [ndom91/react-timezone-select#24]
Hello.

I've just upgraded to 0.10.7 from 0.8.4, and I receive this error.
I'm using it on a NextJS project.
If I revert to 0.8.4 all is working properly.
<img width="1161" alt="Screenshot 2021-03-18 at 13 36 44" src="https://user-images.githubusercontent.com/8121277/111620380-4d5ff580-87ef-11eb-8bee-26d494178b9d.png">

**Comment by shem8** [comment]
Same here

**Comment by ndom91** [comment]
Hey guys thanks for bringing this up! When I'm home this evening I'll give it a look.

**Comment by ndom91** [comment]
Hey guys, so I tried it in a codesandbox with the latest `react`, `next.js`, and `react-timezone-select`, and everything seems alright.

https://codesandbox.io/s/react-timezone-select-test-latest-nextjs-nqikq

Can you share more details about how / where you're using it?

**Comment by ndom91** [comment]
Hey guys, if everything is working or you don't have any new issues, im gonna close this issue in the next few days :+1: 

Feel free to comment to keep it open if you're still having this issue or open a new one!

**Comment by emrysal** [comment]
Hi @ndom91 This also happens for me

**Comment by ndom91** [comment]
@emrysal thanks a lot for digging into this! You're saying defining `type: module` in package.json should fix this? I guess it would tell Next.js's babel that this is explicitly an esmodule and to not try to parse / transpile it with cjs - am I understanding that correctly?

**Comment by emrysal** [comment]
@ndom91 

If you set up your library as pure ESM (without changing all your files to .mjs extension) for the broader NPM community, NextJS currently does not fully support ESM packages yet (but this is actually an issue in NextJS and will be fixed in the future I imagine). For NextJS it'll still not work without also providing a commonJS package from here, but using next-transpile-modules should be good enough for NextJS users.

See:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
https://github.com/sindresorhus/ky-universal/blob/main/package.json
https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1

ky-universal is a pure ESM library, good example

**Comment by ndom91** [comment]
Wow thanks a lot for the follow-up info! 

Maybe this is what Tim is hinting at :wink: https://twitter.com/timneutkens/status/1386622369813483525

**Comment by emrysal** [comment]
@ndom91 There is so many open issues regarding ESM on Next.js (https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aopen+esm) I would be flabbergasted if this was not addressed in the upcoming release.

**Comment by ndom91** [comment]
Released a new version last night with `type:module` in the package.json and a few other cleanup things. 

I also put a hint about the `next-transpile-modules` in the readme. 

Thanks for that! Hopefully next.js fixes this shortly.

**Comment by ndom91** [comment]
Going to close this issue then. 

If anyone comes across this in the future, checkout the workaround in @emrysal 's post above (https://github.com/ndom91/react-timezone-select/issues/24#issuecomment-826699615) 

Or in the README for this project.
